name: Ping Streamlit App

on:
  schedule:
    - cron: "*/15 * * * *"   # Every 15 minutes
  workflow_dispatch:          # Allow manual run

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Streamlit URL
        run: |
          echo "Pinging Streamlit app..."
          curl -f -I https://ml-classification-comparison-q8lgfjznvbqfzbh5lrdqni.streamlit.app/
